color_theme = "catppuccin-mocha"
theme_background = False
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu"
update_ms = 500
show_disks = False
show_battery = False
cpu_single_graph = False
check_temp = False
show_uptime = False
